server:
  port: 8383
  servlet:
    context-path: /shop/api/v1
  error:
    path: /user/error
    whitelabel:
      enabled: false
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shop_api_db
    username: root
    password: root
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
      dialect: org.hibernate.dialect.MySQL8Dialect
      format_sql: true
    generate-ddl: true
